import React  from "react";
import { StyleSheet } from "react-native";

const main = StyleSheet.create({
    header: {
        height: 60,
        width: '100%',
        backgroundColor:'#302F2F'
    },
    headerBox:{
        width:'100%', 
        height:'100%', 
        justifyContent:'flex-start', 
        alignItems:'center',
        paddingLeft:20,
        flexDirection:'row'
    },
    headerBoxTitle:{
        fontSize:18, 
        fontWeight:700, 
        color:'#C4C4BE',
        paddingRight:10
    },
    mainContainer: {
        height:'100%',
        width:'100%',
        backgroundColor:'#242428'
    },
    mainContainerBox:{
        width:'100%', 
        height:50, 
        justifyContent:'center', 
        paddingLeft:20
    },
    mainContainerBoxTitle:{
        fontSize:20, 
        fontWeight:700, 
        color:'#C4C4BE'
    },
    flatlistStyle:{
        marginLeft:20, 
        marginRight:20,  
        paddingBottom:100
    },
    renderMangaStyles:{
        height:200, 
        width:150, 
        marginBottom:20
    },
    renderMangaView:{
        height:175, 
        width:150,  
        borderRadius:15, 
        marginBottom:10,
        backgroundColor:'#f5f5f5'
    },
    title:{
        color:'#C4C4BE',
        fontSize:16,
        fontWeight:'700',
        marginBottom:20,
        marginTop:20
    },
    summary:{
        color:'#C4C4BE',
        fontSize:14,
        fontWeight:'400',
        marginBottom:20,
        lineHeight:18
    },
    chapter:{
        color:'#C4C4BE',
        fontSize:14,
        fontWeight:'400',
        marginBottom:10
    },
    authorContainer:{
        width:'100%', 
        minHeight:10, 
        marginBottom:10,
        flexDirection:'row'
    },
    authorBox:{
        width:'20%', 
        minHeight:10
    },
    authorNameBox:{
        width:'80%', 
        minHeight:10,
        lineHeight:18
    },
    genresContainer:{
        width:'100%', 
        minHeight:10, 
        marginBottom:10,
        flexDirection:'row'
    },
    genresBox:{
        width:'20%', 
        minHeight:10
    },
    genresBox_text:{
        color:'#C4C4BE',
        fontSize:14,
        fontWeight:'400',
    },
    genresListBox:{
        width:'80%', 
        minHeight:10,
        flexDirection:'row', 
        flexWrap:'wrap'
    },
    mangaInfoBox:{
        width:'100%', 
        minHeight:50, 
        justifyContent:'center', 
        paddingTop:20,
        backgroundColor:'#242428'
    },
    genreBoxItem:{
        backgroundColor:'#302F2F', 
        padding:5, 
        paddingLeft:10,  
        paddingRight:10, 
        borderRadius:15, 
        marginRight:5, 
        minWidth:5, 
        borderWidth:1,
        borderColor:'#ccc', 
        marginBottom:10
    },
    chapterItem:{
        borderColor:'#373737', 
        borderBottomWidth:1, 
        height:50, 
        marginTop:10, 
        paddingLeft:15, 
        justifyContent:'center', 
        flexDirection:'row' 
    },
    chapterItemTitle:{
        color:'white', 
        fontSize:14, 
        fontWeight:'600', 
        paddingBottom:5
    },
    mangaTab:{
        height:50, 
        width:'50%', 
        justifyContent:'center', 
        alignItems:'center'
    }
});

export default main;